title: joshuakitchens.com
author: Josh Kitchens
description: Site for archivists Joshua Kitchens. Includes thoughts, information, and educational casestudies.

navbar-links:
  Vita: vita.md

timezone: "America/New_York"
markdown: kramdown
highlighter: rouge

collections:
  cast_studies:
    output: true
    permalink: /:collection/:name/
  posts:
    output: true

remote_theme: pages-themes/cayman@v0.2.0

titles_from_headings:
  enabled:     true
  strip_title: false

plugins:
- jekyll-remote-theme

